# R/07_figures.R  --  figures for the memo (outline Phase 9.4)
#
# Three figures, generated by script and never hand-edited, so every one can be
# regenerated from a fresh clone and traced back to the database.
#   fig1_trend_by_region.png   trust over rounds, small multiples by region
#   fig2_coefficient_plot.png  the panel estimates under three inference layers
#   fig3_coverage_heatmap.png  country x round coverage -- the gaps ARE the point
#
# Usage:  Rscript R/07_figures.R      (from the repository root)
#
# DESIGN NOTES
#   * Figure 1 is FACETED rather than five coloured lines on one panel. Five
#     series on one axis is spaghetti, and a five-hue categorical palette cannot
#     clear colour-blind separation floors on all pairs. Each panel highlights
#     one region against the other four in grey, which keeps the cross-region
#     comparison without relying on hue to carry identity.
#   * Two colours are used anywhere hue must distinguish anything: #2a78d6 and
#     #eb6834. Validated: worst-pair CVD deltaE 24.7 (protan), normal-vision
#     33.6, both well clear of the 8 / 15 floors, and both >= 3:1 on the surface.
#   * Figure 3 uses a single-hue sequential ramp for magnitude and an explicitly
#     EMPTY cell for "not surveyed" -- absence must not read as a low value.

suppressPackageStartupMessages({
  library(DBI); library(duckdb); library(dplyr); library(tidyr); library(ggplot2)
})

DB_PATH <- Sys.getenv("DB_PATH", "data/afrobarometer.duckdb")
FIG_DIR <- Sys.getenv("FIG_DIR", "figures")
OUT_DIR <- Sys.getenv("RESULTS_DIR", "output")

ACCENT   <- "#2a78d6"   # categorical slot 1
ACCENT_2 <- "#eb6834"   # categorical slot 2
SURFACE  <- "#fcfcfb"
INK      <- "#0b0b0b"
INK_2    <- "#52514e"
MUTED    <- "#b9b8b2"

theme_memo <- function(base = 11) {
  theme_minimal(base_size = base) +
    theme(
      plot.background   = element_rect(fill = SURFACE, colour = NA),
      panel.background  = element_rect(fill = SURFACE, colour = NA),
      panel.grid.minor  = element_blank(),
      panel.grid.major  = element_line(colour = "#e7e6e1", linewidth = 0.3),
      axis.title        = element_text(colour = INK_2, size = base - 1),
      axis.text         = element_text(colour = INK_2, size = base - 2),
      plot.title        = element_text(colour = INK, face = "bold", size = base + 2),
      plot.subtitle     = element_text(colour = INK_2, size = base - 1, lineheight = 1.15),
      plot.caption      = element_text(colour = INK_2, size = base - 3, hjust = 0),
      strip.text        = element_text(colour = INK, face = "bold", size = base - 1),
      legend.position   = "top",
      legend.title       = element_blank(),
      legend.text        = element_text(colour = INK_2, size = base - 2),
      plot.title.position = "plot",
      plot.caption.position = "plot"
    )
}

# Two country names carry accents -- Cote d'Ivoire and Sao Tome and Principe.
# In a non-UTF-8 locale the graphics device cannot render multibyte characters
# and silently draws them as dots ("C..te d'Ivoire"), which looks like corrupt
# data rather than a rendering setting. Warn rather than fail: the figures are
# still correct, only two labels are wrong.
check_locale <- function() {
  if (isTRUE(l10n_info()[["UTF-8"]])) return(invisible(TRUE))
  warning("Locale is '", Sys.getlocale("LC_CTYPE"), "', not UTF-8. Accented country ",
          "names will render as dots in the figures.\n",
          "  Linux/macOS: run with  LC_ALL=C.UTF-8 Rscript R/07_figures.R\n",
          "  Windows:     Sys.setlocale('LC_CTYPE', 'English_United States.utf8')",
          call. = FALSE, immediate. = TRUE)
  invisible(FALSE)
}

main <- function() {
  check_locale()
  if (!file.exists(DB_PATH))
    stop("No database at '", DB_PATH, "'. Run Rscript R/05_build_database.R --fresh first.",
         call. = FALSE)
  dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)
  con <- dbConnect(duckdb::duckdb(), DB_PATH, read_only = TRUE)
  on.exit(dbDisconnect(con, shutdown = TRUE), add = TRUE)

  panel    <- dbGetQuery(con, "SELECT * FROM core.analysis_panel")
  coverage <- dbGetQuery(con, "SELECT * FROM core.coverage_grid")

  # ===========================================================================
  # FIGURE 1  --  trust over rounds, small multiples by region
  # Region means are the UNWEIGHTED mean of country-level weighted means, so
  # each country counts once regardless of sample size. The alternative
  # (pooling respondents) would let Nigeria and Sudan dominate their regions.
  # ===========================================================================
  reg <- panel %>%
    group_by(region, round_number) %>%
    summarise(trust = mean(wmean_trust_index, na.rm = TRUE),
              n_countries = n(), .groups = "drop") %>%
    filter(!is.na(region))

  ctx <- reg %>% select(-n_countries) %>% rename(ctx_region = region)

  fig1 <- ggplot(reg, aes(round_number, trust)) +
    geom_line(data = ctx, aes(group = ctx_region),
              colour = MUTED, linewidth = 0.5, alpha = 0.85) +
    geom_line(colour = ACCENT, linewidth = 1.1) +
    geom_point(colour = ACCENT, size = 2.2) +
    facet_wrap(~ region, nrow = 1) +
    scale_x_continuous(breaks = 6:9, labels = paste0("R", 6:9)) +
    labs(
      title    = "Trust in the police and courts, by region",
      subtitle = paste("Mean of country-level survey-weighted means, 0-3 scale.",
                       "Grey lines repeat all five regions in every panel."),
      x = NULL, y = "Trust index (0-3)",
      caption = paste0("Afrobarometer rounds 6-9. Unbalanced panel: ",
                       nrow(panel), " country-rounds across ",
                       dplyr::n_distinct(panel$country_id), " countries.\n",
                       "Descriptive. Round fieldwork spans 1-2 years, so rounds are waves, not years.")
    ) + theme_memo()
  ggsave(file.path(FIG_DIR, "fig1_trend_by_region.png"), fig1,
         width = 11, height = 3.6, dpi = 200, bg = SURFACE)

  # ===========================================================================
  # FIGURE 2  --  coefficient plot, three inference layers
  # The point of the figure is that the corruption estimate's interval crosses
  # zero under EVERY layer and the performance estimate's never does. Intervals
  # are +/- 1.96 SE for CR1 and the Satterthwaite-t critical value for CR2, so
  # the widening from the small-cluster correction is visible rather than
  # asserted. The bootstrap has no interval -- it is a test -- so its p-value
  # is printed rather than drawn.
  # ===========================================================================
  res_path <- file.path(OUT_DIR, "panel_twoway_fe_inference.csv")
  if (!file.exists(res_path))
    stop("Missing ", res_path, " - run Rscript R/06_analysis.R first.", call. = FALSE)
  res <- read.csv(res_path)

  ci <- res %>%
    transmute(sample, term,
              estimate,
              lo_cr1 = estimate - 1.96 * se_cr1, hi_cr1 = estimate + 1.96 * se_cr1,
              lo_cr2 = estimate - qt(0.975, df_satt) * se_cr2,
              hi_cr2 = estimate + qt(0.975, df_satt) * se_cr2,
              p_wildboot) %>%
    mutate(term = recode(term,
             wmean_corruption_govt   = "Perceived corruption\n(government officials)",
             wmean_govt_perf_economy = "Perceived government\nperformance (economy)"),
           sample = factor(sample, levels = c("full (unbalanced)", "balanced")))

  # Two intervals per sample, drawn at a vertical offset rather than stacked on
  # one line: CR2 is NARROWER than CR1 here (its smaller standard error more than
  # offsets the Satterthwaite degrees-of-freedom penalty), so overlaying them
  # buries the thin bar and the comparison is lost.
  ci_long <- ci %>%
    tidyr::pivot_longer(c(lo_cr1, hi_cr1, lo_cr2, hi_cr2),
                        names_to = c(".value", "layer"), names_sep = "_") %>%
    mutate(layer = recode(layer, cr1 = "cluster-robust (CR1)",
                                 cr2 = "CR2 + Satterthwaite"),
           layer = factor(layer, levels = c("cluster-robust (CR1)", "CR2 + Satterthwaite")),
           nudge = ifelse(layer == "cluster-robust (CR1)", 0.16, -0.16))

  fig2 <- ggplot(ci, aes(y = sample)) +
    geom_vline(xintercept = 0, colour = INK_2, linewidth = 0.4, linetype = "22") +
    geom_linerange(data = ci_long,
                   aes(xmin = lo, xmax = hi, y = sample, colour = sample,
                       linewidth = layer),
                   position = position_nudge(y = ci_long$nudge)) +
    geom_point(aes(x = estimate, colour = sample), size = 3.2) +
    geom_text(aes(x = estimate,
                  label = sprintf("%.3f   (bootstrap p = %.3f)", estimate, p_wildboot)),
              vjust = 2.9, size = 3, colour = INK_2) +
    facet_wrap(~ term, ncol = 1, scales = "free_y") +
    scale_colour_manual(values = c("full (unbalanced)" = ACCENT, "balanced" = ACCENT_2),
                        guide = "none") +
    scale_linewidth_manual(values = c("cluster-robust (CR1)" = 0.6,
                                      "CR2 + Satterthwaite" = 2.0), name = NULL) +
    scale_y_discrete(expand = expansion(add = 0.75)) +
    guides(linewidth = guide_legend(override.aes = list(colour = INK_2))) +
    labs(
      title    = "Two-way fixed-effect estimates under three inference layers",
      subtitle = paste("Intervals are 95%. The bootstrap is a test, not an interval,",
                       "so its p-value is printed at each estimate.\n",
                       "Country and round fixed effects; standard errors clustered on country."),
      x = "Association with trust in police and courts (0-3 scale)", y = NULL,
      caption = paste0("36 country clusters (full) and 31 (balanced) after dropping fixed-effect singletons. ",
                       "All three layers agree:\nthe corruption interval crosses zero, the performance interval does not. ",
                       "DESCRIPTIVE -- these are not causal effects.")
    ) + theme_memo()
  ggsave(file.path(FIG_DIR, "fig2_coefficient_plot.png"), fig2,
         width = 8.5, height = 5.4, dpi = 200, bg = SURFACE)

  # ===========================================================================
  # FIGURE 3  --  coverage heatmap. The empty cells are the finding.
  # Sequential single hue encodes sample size; "not surveyed" is drawn as an
  # empty cell with a hairline border, so absence cannot be mistaken for a low
  # value -- which is exactly what a zero-coloured cell would imply.
  # ===========================================================================
  cov <- coverage %>%
    mutate(country_name = factor(country_name, levels = rev(sort(unique(country_name)))),
           surveyed = status == "surveyed")

  fig3 <- ggplot(cov, aes(factor(round_number), country_name)) +
    geom_tile(fill = SURFACE, colour = "#e0dfd9", linewidth = 0.4) +
    geom_tile(data = filter(cov, surveyed), aes(fill = n_respondents),
              colour = SURFACE, linewidth = 0.8) +
    scale_fill_gradient(low = "#cfe0f5", high = "#1d5aa3", name = "respondents",
                        labels = scales::comma) +
    scale_x_discrete(labels = paste0("R", 6:9), position = "top") +
    labs(
      title    = "Country coverage across rounds",
      subtitle = paste0("Empty cells are countries not surveyed in that round. ",
                        sum(!cov$surveyed), " of ", nrow(cov), " possible country-rounds are empty;\n",
                        "only ", sum(table(cov$country_name[cov$surveyed]) == 4),
                        " countries appear in all four rounds and enter the balanced panel."),
      x = NULL, y = NULL,
      caption = "The gaps determine whether any cross-round comparison is balanced."
    ) + theme_memo() +
    theme(panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 7),
          legend.position = "right", legend.title = element_text(colour = INK_2, size = 8))
  ggsave(file.path(FIG_DIR, "fig3_coverage_heatmap.png"), fig3,
         width = 7.5, height = 9, dpi = 200, bg = SURFACE)

  message("Figures written to ", FIG_DIR, "/:")
  for (f in list.files(FIG_DIR, "\\.png$")) message("  ", f)
}

main()
